# Generated by Django 3.2.11 on 2022-03-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('atribuicoes', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=7, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='Bairro/Distrito')),
                ('cidade', models.CharField(blank=True, max_length=30)),
                ('uf', models.CharField(blank=True, choices=[('ac', 'AC'), ('al', 'AL'), ('ap', 'AP'), ('am', 'AM'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('rs', 'RS'), ('ro', 'RO'), ('rr', 'RR'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('apelido', models.CharField(blank=True, max_length=20)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Limite de Crédito')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('localizacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=7, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='Bairro/Distrito')),
                ('cidade', models.CharField(blank=True, max_length=30)),
                ('uf', models.CharField(blank=True, choices=[('ac', 'AC'), ('al', 'AL'), ('ap', 'AP'), ('am', 'AM'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('rs', 'RS'), ('ro', 'RO'), ('rr', 'RR'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('pis', models.IntegerField()),
                ('numero_ctps', models.IntegerField(verbose_name='Número')),
                ('serie_ctps', models.IntegerField(verbose_name='Série')),
                ('admissao', models.DateField(verbose_name='Admissão')),
                ('CBO', models.IntegerField()),
                ('cadastro', models.IntegerField()),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Remuneração')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.setor'),
        ),
    ]
