# Generated by Django 3.2.11 on 2022-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg',
            field=models.IntegerField(unique=True),
        ),
    ]
