# Generated by Django 3.2.11 on 2022-03-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20220127_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricacao',
            new_name='descricao',
        ),
    ]
