# Generated by Django 3.2.11 on 2022-03-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_descricacao_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Empresarial')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, verbose_name='Nome Fantasia')),
                ('logradouro', models.CharField(blank=True, max_length=30)),
                ('numero', models.CharField(blank=True, max_length=7, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='Bairro/Distrito')),
                ('cidade', models.CharField(blank=True, max_length=30)),
                ('uf', models.CharField(blank=True, choices=[('ac', 'AC'), ('al', 'AL'), ('ap', 'AP'), ('am', 'AM'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('rs', 'RS'), ('ro', 'RO'), ('rr', 'RR'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=12)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
